"""Pydantic models for siRNA design data structures."""

from .evidence import (
    EVIDENCE_SCHEMA_VERSION,
    EvidenceStatus,
    ObservedCounts,
    ScreeningEvidence,
    ScreeningEvidenceEntry,
    ScreeningPlan,
    ScreeningPlanEntry,
)
from .modifications import (
    ChemicalModification,
    ConfirmationStatus,
    Provenance,
    SequenceRecord,
    SourceType,
    StrandMetadata,
    StrandRole,
)
from .off_target import (
    AggregatedMiRNASummary,
    AggregatedOffTargetSummary,
    AlignmentStrand,
    AnalysisMode,
    AnalysisSummary,
    MiRNADatabase,
    MiRNAHit,
    MiRNASummary,
    OffTargetHit,
)
from .policy import (
    DEFAULT_TARGET_SPECIES,
    EvidenceRequirements,
    FilterAction,
    FilterEvaluation,
    RunMode,
    ScreeningChannel,
    TargetIntent,
)
from .sirna import (
    DesignMode,
    DesignParameters,
    DesignResult,
    DesignWeights,
    FilterCriteria,
    MiRNADesignConfig,
    PostScreenMiRNAWeights,
    PostScreenSiRNAWeights,
    ScoringWeights,
    SequenceType,
    SiRNACandidate,
    WeightVector,
)
from .transcript_annotation import Interval, TranscriptAnnotation, TranscriptAnnotationBundle
from .variant import (
    ClinVarSignificance,
    VariantMode,
    VariantQuery,
    VariantQueryType,
    VariantRecord,
    VariantSource,
)
from .zfn import (
    DimerMode,
    GenomicAnnotationConfig,
    IUPACMode,
    MatchOrientation,
    Strand,
    ZFNAlgorithm,
    ZFNCandidate,
    ZFNDesignParameters,
    ZFNDesignResult,
    ZFNHalfSiteConstraints,
    ZFNOffTargetFilterCriteria,
    ZFNOffTargetSite,
    ZFNScoringWeights,
    ZFNSpacerConstraints,
)

__all__ = [
    # siRNA design models
    "DesignMode",
    "DesignParameters",
    "DesignResult",
    "DesignWeights",
    "FilterCriteria",
    "MiRNADesignConfig",
    "PostScreenMiRNAWeights",
    "PostScreenSiRNAWeights",
    "ScoringWeights",
    "SequenceType",
    "SiRNACandidate",
    "WeightVector",
    # Chemical modification models
    "ChemicalModification",
    "ConfirmationStatus",
    "Provenance",
    "SequenceRecord",
    "SourceType",
    "StrandMetadata",
    "StrandRole",
    # Off-target analysis models
    "OffTargetHit",
    "MiRNAHit",
    "AnalysisSummary",
    "MiRNASummary",
    "AggregatedOffTargetSummary",
    "AggregatedMiRNASummary",
    "AlignmentStrand",
    "AnalysisMode",
    "MiRNADatabase",
    # Run policy contracts (#99/#101 vocabulary)
    "DEFAULT_TARGET_SPECIES",
    "RunMode",
    "FilterAction",
    "FilterEvaluation",
    "ScreeningChannel",
    "TargetIntent",
    "EvidenceRequirements",
    # Screening plan/evidence contracts (#100 vocabulary)
    "EVIDENCE_SCHEMA_VERSION",
    "EvidenceStatus",
    "ObservedCounts",
    "ScreeningPlanEntry",
    "ScreeningPlan",
    "ScreeningEvidenceEntry",
    "ScreeningEvidence",
    # Transcript annotation models
    "Interval",
    "TranscriptAnnotation",
    "TranscriptAnnotationBundle",
    # Variant models
    "VariantRecord",
    "VariantQuery",
    "VariantQueryType",
    "VariantMode",
    "VariantSource",
    "ClinVarSignificance",
    # ZFN models
    "Strand",
    "DimerMode",
    "ZFNAlgorithm",
    "MatchOrientation",
    "IUPACMode",
    "ZFNHalfSiteConstraints",
    "ZFNSpacerConstraints",
    "ZFNOffTargetFilterCriteria",
    "ZFNScoringWeights",
    "ZFNDesignParameters",
    "GenomicAnnotationConfig",
    "ZFNOffTargetSite",
    "ZFNCandidate",
    "ZFNDesignResult",
]
